SET local check_function_bodies = off;

CREATE TABLE "public"."analytics" (
  "id"              uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_identifier" text,
  "country"         character varying(10),
  "device"          text                     NOT NULL,
  "browser"         text,
  "path"            text                     NOT NULL,
  "details"         jsonb,
  "created_at"      timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "analytics_pkey" PRIMARY KEY (id),
  CONSTRAINT "analytics_user_identifier_key" UNIQUE (user_identifier)
);

ALTER TABLE "public"."analytics"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."contact_queries" (
  "id"         uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "origin"     text                     NOT NULL DEFAULT 'adi'::text,
  "SenderName" text                     NOT NULL,
  "email"      text                     NOT NULL,
  "message"    text                     NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "status"     text                     DEFAULT 'pending'::text,
  CONSTRAINT "contact_queries_email_check" CHECK ((email ~* '@'::text)),
  CONSTRAINT "contact_queries_origin_check" CHECK ((origin = ANY (ARRAY['smug'::text, 'adi'::text]))),
  CONSTRAINT "contact_queries_pending_check" CHECK ((status = ANY (ARRAY['pending'::text, 'contacted'::text, 'ignore'::text]))),
  CONSTRAINT "contact_queries_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."contact_queries"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."personal_blogs_drafts" (
  "id"               uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "title"            text                     NOT NULL DEFAULT ''::text,
  "shortDescription" text                     NOT NULL DEFAULT ''::text,
  "content"          text                     NOT NULL DEFAULT ''::text,
  "banner"           text,
  "published"        timestamp with time zone DEFAULT now(),
  "updated"          timestamp with time zone,
  "isdraft"          boolean                  DEFAULT true,
  CONSTRAINT "personal_blogs_drafts_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."personal_blogs_drafts"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."personal_blogs" (
  "id"               uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "title"            text                     NOT NULL DEFAULT ''::text,
  "shortDescription" text                     NOT NULL DEFAULT ''::text,
  "content"          text                     NOT NULL DEFAULT ''::text,
  "banner"           text,
  "published"        timestamp with time zone DEFAULT now(),
  "updated"          timestamp with time zone,
  "isdraft"          boolean                  DEFAULT false,
  CONSTRAINT "personal_blogs_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."personal_blogs"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."personal_projects_drafts" (
  "id"                    uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "orderIndex"            integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title"                 text,
  "Link"                  text,
  "tags"                  json,
  "started"               text,
  "ended"                 text,
  "DemoVideo"             text,
  "image"                 text,
  "Description"           text,
  "AdditionalDescription" text,
  "content"               text,
  "links"                 json,
  "created_at"            timestamp with time zone NOT NULL DEFAULT now(),
  "isdraft"               boolean                  DEFAULT true,
  CONSTRAINT "personal_projects_drafts_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."personal_projects_drafts"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."personal_projects" (
  "id"                    uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "orderIndex"            integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title"                 text,
  "Link"                  text,
  "tags"                  json,
  "started"               text,
  "ended"                 text,
  "DemoVideo"             text,
  "image"                 text,
  "Description"           text,
  "AdditionalDescription" text,
  "content"               text,
  "links"                 json,
  "created_at"            timestamp with time zone NOT NULL DEFAULT now(),
  "isdraft"               boolean                  DEFAULT false,
  CONSTRAINT "personal_projects_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."personal_projects"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."public_assets" (
  "id"         uuid                     DEFAULT gen_random_uuid(),
  "url"        text,
  "created_at" timestamp with time zone DEFAULT now(),
  "path"       text
);

ALTER TABLE "public"."public_assets"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."update_logs_testing" (
  "id"          uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "last_update" timestamp with time zone NOT NULL DEFAULT now(),
  "log"         text,
  CONSTRAINT "update_logs_testing_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."update_logs_testing"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."update_logs" (
  "id"          uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "last_update" timestamp with time zone NOT NULL DEFAULT now(),
  "log"         text,
  CONSTRAINT "udpate_logs_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."update_logs"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."users" (
  "id"         uuid                     NOT NULL,
  "role"       text                     DEFAULT 'user'::text,
  "full_name"  text,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "users_pkey" PRIMARY KEY (id),
  CONSTRAINT "users_role_check" CHECK ((role = ANY (ARRAY['user'::text, 'admin'::text])))
);

ALTER TABLE "public"."users"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
  AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

ALTER TABLE "public"."users"
  ADD CONSTRAINT "users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE POLICY "Public anonymous insert" ON "public"."analytics"
  FOR INSERT
  TO "anon"
  WITH CHECK (true);

CREATE POLICY "Authenticated can select" ON "public"."contact_queries"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Authenticated can update" ON "public"."contact_queries"
  FOR UPDATE
  TO "authenticated"
  USING (true);

CREATE POLICY "anon can insert" ON "public"."contact_queries"
  FOR INSERT
  TO "anon"
  WITH CHECK (true);

CREATE POLICY "Authenticated can select" ON "public"."personal_blogs"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "authenticated can delete" ON "public"."personal_blogs"
  FOR DELETE
  TO "authenticated"
  USING (true);

CREATE POLICY "authenticated can insert" ON "public"."personal_blogs"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "annon_can_see_blogs" ON "public"."personal_blogs"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "authenticated can delete" ON "public"."personal_blogs_drafts"
  FOR DELETE
  TO "authenticated"
  USING (true);

CREATE POLICY "authenticated can insert" ON "public"."personal_blogs_drafts"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "authenticated can select" ON "public"."personal_blogs_drafts"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "authenticated can update" ON "public"."personal_blogs_drafts"
  FOR UPDATE
  TO "authenticated"
  USING (true);

CREATE POLICY "Authenticated can insert" ON "public"."personal_projects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Authenticated can select" ON "public"."personal_projects"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "annon can see" ON "public"."personal_projects"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "authenticated can update" ON "public"."personal_projects"
  FOR UPDATE
  TO "authenticated"
  USING (true);

CREATE POLICY "authenticated can delete" ON "public"."personal_projects_drafts"
  FOR DELETE
  TO "authenticated"
  USING (true);

CREATE POLICY "authenticated can insert" ON "public"."personal_projects_drafts"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "authenticated can select" ON "public"."personal_projects_drafts"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "authenticated can update" ON "public"."personal_projects_drafts"
  FOR UPDATE
  TO "authenticated"
  USING (true);

CREATE POLICY "Authenticated can Insert" ON "public"."public_assets"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Authenticated can delete" ON "public"."public_assets"
  FOR DELETE
  TO "authenticated"
  USING (true);

CREATE POLICY "Authenticated can select" ON "public"."public_assets"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "admin can insert" ON "public"."update_logs"
  FOR INSERT
  TO "service_role"
  WITH CHECK (true);

CREATE POLICY "anon can read logs" ON "public"."update_logs"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "service can insert" ON "public"."update_logs_testing"
  FOR INSERT
  TO "service_role"
  WITH CHECK (true);

CREATE POLICY "authenticated can see" ON "public"."users"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Authenticated can modify  1bqp9qb_0" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((bucket_id = 'assets'::text));

CREATE POLICY "Authenticated can modify  1bqp9qb_2" ON "storage"."objects"
  FOR UPDATE
  TO "authenticated"
  USING ((bucket_id = 'assets'::text));

CREATE POLICY "Authenticated can modify  1bqp9qb_3" ON "storage"."objects"
  FOR DELETE
  TO "authenticated"
  USING ((bucket_id = 'assets'::text));

CREATE EVENT TRIGGER "ensure_rls"
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION "public"."rls_auto_enable"();

COMMENT ON TABLE "public"."personal_blogs_drafts" IS 'This is a duplicate of personal_blogs';

COMMENT ON TABLE "public"."personal_projects_drafts" IS 'This is a duplicate of personal_projects';

COMMENT ON TABLE "public"."update_logs_testing" IS 'This is a duplicate of update_logs';

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."analytics" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."contact_queries" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."personal_blogs" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."personal_blogs_drafts" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."personal_projects" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."personal_projects_drafts" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."public_assets" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."update_logs" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."update_logs_testing" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users" TO "anon", "authenticated", "postgres", "service_role";

